import SectionHeader from '../components/SectionHeader'
import Divider from '../components/Divider'
import Footer from '../components/Footer'

const valueChain = [
  { name: 'Farmer Cluster', sub: '3A Cooperative', device: 'Feature phone (USSD/SMS) or smartphone (PWA)', identity: 'Mobile money binding (preferred) or SIM OTP',
    writes: 'Accept contracts (via vote), confirm deliveries (handshake), vote on proposals, file disputes',
    sees: 'Own contracts, deliveries, payouts (waterfall breakdown), trust score + breakdown, governance (treasury, proposals, votes, constitution)',
    blind: 'Other clusters\' data. Contract prices offered to other clusters. Processor margins.' },
  { name: 'Processor', sub: 'Anchor Buyer', device: 'Desktop or tablet (PWA)', identity: 'Google OAuth or SIM OTP',
    writes: 'Post forward contracts, confirm deliveries (handshake), trigger payment waterfall',
    sees: 'Own contracts and fulfilment, aggregate committed tonnage by cluster tier, payment obligations, quality results, own trust score, counterparty trust tiers',
    blind: 'Farmer input costs, loan balances, cluster treasury details, other processors\' contracts' },
  { name: 'Depot Operator', sub: 'Warehouse', device: 'Tablet or smartphone (PWA)', identity: 'SIM OTP',
    writes: 'Confirm deliveries (handshake), record quality tests (attestation)',
    sees: 'Intake schedule, current inventory by grade, custody fee accrual, dispatch schedule, own trust score',
    blind: 'Forward contract prices, farmer payouts, loan balances' },
  { name: 'Input Supplier', sub: 'Seed & Fertiliser', device: 'Tablet or smartphone (PWA)', identity: 'SIM OTP',
    writes: 'Record input advances, confirm input delivery (handshake)',
    sees: 'Outstanding advances, repayment status, linked forward contracts (proving the cluster has a buyer), own trust score',
    blind: 'Farmer payouts beyond their own repayment line' },
  { name: 'Insurer', sub: 'ZIRSAT / Commercial', device: 'Desktop (PWA)', identity: 'Google OAuth',
    writes: 'Underwrite contracts, set premiums, process claims',
    sees: 'Portfolio, claims history, actuarial data (delivery reliability, loss ratios), national trust distribution',
    blind: 'Individual farmer payouts, cluster treasury, specific loan balances' },
]

const government = [
  { name: 'Extension Officer', sub: 'Camp Level', device: 'Smartphone (PWA)', identity: 'SIM OTP or Google OAuth',
    writes: 'Training sessions (attestation), monitoring visits (attestation), advisory records (attestation), issue flags, mediates disputes (Tier 2)',
    sees: 'Assigned clusters — membership, trust tier (NOT score number), delivery performance, quality results, training coverage',
    blind: 'Financial data of any kind. No payouts, no loan balances, no treasury transactions, no contract prices.' },
  { name: 'District Coordinator', sub: 'DDCC Level', device: 'Desktop or tablet (PWA)', identity: 'Google OAuth',
    writes: 'Cluster registration approvals, issue escalations',
    sees: 'All clusters in district, extension officer activity, implementing partner activity, aggregate financial data (SAFF utilisation, payment volumes), dispute rates, early warnings, anomaly flags',
    blind: 'Individual farmer payouts, scores, or loan balances' },
  { name: 'Provincial Coordinator', sub: 'Province Level', device: 'Desktop (PWA)', identity: 'Google OAuth',
    writes: 'Provincial issue escalations',
    sees: 'Province-wide aggregates, district comparison, partner coverage, early warnings',
    blind: 'Individual-level data of any kind' },
  { name: 'ZARETA', sub: 'National', device: 'Desktop (PWA)', identity: 'Google OAuth',
    writes: 'Policy configuration, partner approvals',
    sees: 'National aggregates, cross-provincial comparisons, all partner performance, programme KPIs, full anomaly dashboard, audit trail, case analytics, price discovery data',
    blind: 'Individual farmer-level financial data' },
  { name: 'HCAT / CSC', sub: 'Minister / Cabinet', device: 'PDF reports', identity: 'N/A — reports generated by ZARETA',
    writes: 'Nothing — read-only via PDF',
    sees: 'Executive dashboard: 5-10 KPIs, traffic light by province, trend lines',
    blind: 'Everything below national aggregate level' },
]

const service = [
  { name: 'Implementing Partner', sub: 'Musika, Agova, EcoAfri, etc.', device: 'Desktop and smartphone (PWA)', identity: 'Google OAuth',
    writes: 'Service delivery records (attestation), training sessions (attestation), issue flags',
    sees: 'Assigned clusters — trust tier, delivery performance, quality data, own service delivery records, outcome data for impact attribution',
    blind: 'Financial data. No payouts, no loans, no treasury. Same blindness as extension officers.' },
  { name: 'ZATTF Staff', sub: 'ZIFSAT / ZIRSAT / ZINFSAT', device: 'Desktop (PWA)', identity: 'Google OAuth',
    writes: 'Facility-specific approvals and configuration',
    sees: 'Facility-specific portfolio data, aggregate national metrics, implementing partner performance (ZINFSAT), loan portfolio health (ZIFSAT), actuarial data (ZIRSAT)',
    blind: 'Individual farmer-level data outside facility scope' },
]

function ParticipantCard({ p, accent }) {
  return (
    <div className="agent-card" style={{ borderColor: accent }}>
      <div className="agent-name">{p.name}</div>
      <div className="agent-channel">{p.sub}</div>
      <div style={{ fontSize: 11, color: 'var(--t4)', marginBottom: 10 }}>{p.device} &middot; {p.identity}</div>
      <div style={{ marginBottom: 8 }}>
        <div style={{ fontSize: 10, fontWeight: 500, letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--eg-hi)', marginBottom: 3 }}>Writes</div>
        <div style={{ fontSize: 12, color: 'var(--t2)', lineHeight: '1.6' }}>{p.writes}</div>
      </div>
      <div style={{ marginBottom: 8 }}>
        <div style={{ fontSize: 10, fontWeight: 500, letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--cu-lt)', marginBottom: 3 }}>Sees</div>
        <div style={{ fontSize: 12, color: 'var(--t2)', lineHeight: '1.6' }}>{p.sees}</div>
      </div>
      <div>
        <div style={{ fontSize: 10, fontWeight: 500, letterSpacing: '.12em', textTransform: 'uppercase', color: 'var(--red)', marginBottom: 3 }}>Does Not See</div>
        <div style={{ fontSize: 12, color: 'var(--t4)', lineHeight: '1.6' }}>{p.blind}</div>
      </div>
    </div>
  )
}

function GroupLabel({ label }) {
  return (
    <div style={{ fontSize: 11, fontWeight: 500, letterSpacing: '.3em', textTransform: 'uppercase', color: 'var(--cu-lt)', marginTop: 34, marginBottom: 13, paddingBottom: 8, borderBottom: '1px solid var(--s3)' }}>
      {label}
    </div>
  )
}

export default function ParticipantsPage() {
  return (
    <>
      <SectionHeader id="participants" num="03" title="Participants" sub="What each person sees — and what they're blind to" />

      <section className="sec">
        <div className="eye">12 Participant Types</div>
        <h2 className="h2">Everyone uses the same system. Nobody sees the same thing.</h2>
        <p className="p">Each participant type maps to a preset — a named collection of capabilities with defined scopes. The descriptions below define the intent. The capability registry enforces it.</p>

        <GroupLabel label="Value Chain" />
        <div className="agent-grid">
          {valueChain.map(p => <ParticipantCard key={p.name} p={p} accent="var(--eg-mid)" />)}
        </div>

        <GroupLabel label="Government &amp; Coordination" />
        <div className="agent-grid">
          {government.map(p => <ParticipantCard key={p.name} p={p} accent="var(--cu)" />)}
        </div>

        <GroupLabel label="Service Delivery" />
        <div className="agent-grid">
          {service.map(p => <ParticipantCard key={p.name} p={p} accent="var(--eg-br)" />)}
        </div>
      </section>

      <Divider />

      {/* The Privacy Principle */}
      <div className="sec-eg">
        <div className="inner">
          <div className="eye" style={{ color: 'var(--cu-hi)' }}>The Privacy Principle</div>
          <h2 className="h2">Nobody sees the farmer's money.</h2>
          <div className="pull" style={{ borderColor: 'var(--cu-lt)', color: 'rgba(242,237,230,.75)' }}>
            The closer you are to the farmer, the more you see about their farming — but <em>nobody at any level sees their money.</em>
          </div>
          <p className="p" style={{ color: 'rgba(242,237,230,.65)' }}>
            Extension officers see crop performance and quality because they need it to advise. They never see what the farmer was paid, their loan balance, or their trust score number. This prevents rent-seeking.
          </p>
          <p className="p" style={{ color: 'rgba(242,237,230,.65)' }}>
            District coordinators and above see aggregate financial data — SAFF utilisation rates, total payment volumes — but never individual farmer payouts or balances. The <strong style={{ color: 'var(--t1)' }}>financial.view</strong> capability at district scope or above returns aggregates only, enforced at the database level.
          </p>
        </div>
      </div>

      <Divider />
      <Footer />
    </>
  )
}
